import { MetadataRoute } from 'next';

const blogPosts = [
  { slug: "01-ai-content-strategy", title: "The Complete AI Content Strategy for 2026", date: "2026-01-15" },
  { slug: "02-brand-voice-consistency", title: "Maintaining Brand Voice Consistency Across All Channels", date: "2026-01-22" },
  { slug: "03-productivity-hacks", title: "10 Productivity Hacks for Content Creators in 2026", date: "2026-02-01" },
  { slug: "04-seo-fundamentals", title: "SEO Fundamentals That Still Matter in 2026", date: "2026-02-10" },
  { slug: "05-future-of-writing", title: "The Future of Writing: Human-AI Collaboration", date: "2026-02-20" },
  { slug: "06-ai-writing-for-email-marketing", title: "AI Writing for Email Marketing: Boost Open Rates with Better Copy", date: "2026-05-25" },
  { slug: "07-overcoming-writers-block-with-ai", title: "How to Overcome Writer's Block with AI: A Practical Guide", date: "2026-05-25" },
  { slug: "08-ai-content-strategy-2026", title: "Building an AI-Powered Content Strategy in 2026", date: "2026-05-25" },
  { slug: "09-ai-vs-human-writers", title: "AI vs. Human Writers: Why the Future is Collaborative, Not Competitive", date: "2026-05-25" },
  { slug: "10-multilingual-ai-writing", title: "Breaking Language Barriers: How AI Writing Tools Handle 50+ Languages", date: "2026-05-25" },
  { slug: "11-seo-ai-writing-best-practices", title: "SEO and AI Writing: Best Practices for Ranking in 2026", date: "2026-05-25" },
  { slug: "12-ai-writing-for-social-media-managers", title: "AI Writing Tools Every Social Media Manager Needs in 2026", date: "2026-05-25" },
  { slug: "13-how-to-train-ai-on-your-writing-style", title: "How to Train AI on Your Writing Style: The Complete Guide", date: "2026-05-25" },
  { slug: "14-ai-writing-api-integration", title: "Integrating AI Writing APIs into Your Workflow: A Developer's Guide", date: "2026-05-25" },
  { slug: "15-future-of-content-creation-ai", title: "The Future of Content Creation: Why AI Is the New Normal", date: "2026-05-25" },
  { slug: "how-to-write-blog-posts-with-ai", title: "How to Write Blog Posts with AI: The Complete Guide", date: "2026-05-25" },
  { slug: "claude-vs-deepseek-for-writing", title: "Claude vs DeepSeek for Content Writing: Which Should You Use?", date: "2026-05-25" },
  { slug: "ai-writing-tools-affordable", title: "Affordable AI Writing Tools That Don't Suck (2026 Edition)", date: "2026-05-25" },
  { slug: "brand-voice-ai-writing", title: "Brand Voice AI Writing: How to Create Your Digital Twin", date: "2026-05-25" },
  { slug: "ai-writing-for-startup-founders", title: "AI Writing for Startup Founders", date: "2026-05-25" },
  { slug: "ai-writing-ethics-transparency", title: "The Ethics of AI Writing", date: "2026-05-25" },
  { slug: "ai-writing-tools-for-non-native-speakers", title: "Best AI Writing Tools for Non-Native Speakers", date: "2026-05-25" },
  { slug: "how-to-choose-ai-writing-tool", title: "How to Choose the Right AI Writing Tool", date: "2026-05-25" },
  { slug: "ai-writing-for-ecommerce", title: "AI Writing for E-commerce", date: "2026-05-25" },
  { slug: "ai-writing-myths-debunked", title: "5 AI Writing Myths Debunked", date: "2026-05-25" },
  { slug: "ai-writing-for-academic-research", title: "AI Writing Tools for Academic Research", date: "2026-05-25" },
  { slug: "personal-brand-building-with-ai", title: "Building a Personal Brand with AI", date: "2026-05-25" },
  { slug: "ai-writing-for-newsletters", title: "How to Write Newsletters with AI", date: "2026-05-25" },
  { slug: "ai-writing-trends-to-watch", title: "7 AI Writing Trends to Watch in 2026", date: "2026-05-25" },
  { slug: "ai-writing-for-freelancers", title: "AI Writing for Freelancers: How to 10x Your Output Without Burning Out", date: "2026-05-25" },
  { slug: "claude-sonnet-4-writing-quality", title: "Claude Sonnet 4.6 for Writing: An Honest Quality Review", date: "2026-05-25" },
  { slug: "ai-writing-tools-comparison-2026", title: "The Ultimate AI Writing Tools Comparison: Jasper vs Copy.ai vs Use AI Writer (2026)", date: "2026-05-25" },
  { slug: "ai-writing-for-linkedin", title: "How to Use AI for LinkedIn Posts That Actually Get Engagement", date: "2026-05-25" },
  { slug: "ai-writing-seo-mistakes", title: "7 Common AI Writing SEO Mistakes and How to Avoid Them", date: "2026-05-25" },
  { slug: "ai-writing-for-youtube-scripts", title: "Writing YouTube Scripts with AI: From Outline to Final Draft", date: "2026-05-25" },
  { slug: "ai-writing-tools-for-teams", title: "Best AI Writing Tools for Teams: Collaboration Features That Matter", date: "2026-05-25" },
  { slug: "ai-writing-privacy-security", title: "AI Writing and Privacy: What Happens to Your Data?", date: "2026-05-25" },
  { slug: "ai-writing-for-bloggers", title: "AI Writing for Bloggers: How to Scale Without Losing Your Voice", date: "2026-05-25" },
  { slug: "ai-writing-future-2027-predictions", title: "AI Writing in 2027: 10 Predictions That Will Surprise You", date: "2026-05-25" },
  { slug: "ai-writing-for-real-estate-agents", title: "AI Writing for Real Estate Agents: Property Descriptions That Sell", date: "2026-05-25" },
  { slug: "ai-writing-for-lawyers", title: "AI Writing for Lawyers: Drafting Briefs and Client Communications", date: "2026-05-25" },
  { slug: "ai-writing-for-medical-professionals", title: "AI Writing for Medical Professionals: Patient Communication Made Clear", date: "2026-05-25" },
  { slug: "ai-writing-for-coaches", title: "AI Writing for Coaches: How to Scale Your Content Without Losing Authenticity", date: "2026-05-25" },
  { slug: "ai-writing-tools-open-source", title: "Open Source AI Writing Tools vs. Paid: Which Should You Choose?", date: "2026-05-25" },
  { slug: "ai-writing-for-podcasters", title: "AI Writing for Podcasters: Show Notes, Scripts, and Social Posts", date: "2026-05-25" },
  { slug: "deepseek-v3-vs-claude-sonnet-4", title: "DeepSeek V3.2 vs Claude Sonnet 4.6: Honest Writing Quality Comparison", date: "2026-05-25" },
  { slug: "ai-writing-for-e-learning", title: "AI Writing for E-Learning: Creating Course Content That Engages", date: "2026-05-25" },
  { slug: "ai-writing-for-nonprofits", title: "AI Writing for Nonprofits: Crafting Compelling Grant Proposals", date: "2026-05-25" },
  { slug: "ai-writing-for-technical-documentation", title: "AI Writing for Technical Documentation: Clarity Meets Accuracy", date: "2026-05-25" },
  { slug: "ai-writing-for-video-marketing", title: "AI Writing for Video Marketing: Scripts, Descriptions, and Captions", date: "2026-05-25" },
  { slug: "how-to-spot-ai-generated-text", title: "How to Spot AI-Generated Text: A Guide for Editors and Teachers", date: "2026-05-25" },
  { slug: "ai-writing-for-customer-support", title: "AI Writing for Customer Support: Templates That Sound Human", date: "2026-05-25" },
  { slug: "ai-writing-for-internal-comms", title: "AI Writing for Internal Communications: Memos, Updates, and Reports", date: "2026-05-25" },
  { slug: "ai-writing-tools-enterprise", title: "AI Writing Tools for Enterprise: Security, Compliance, and Scale", date: "2026-05-25" },
  { slug: "ai-writing-for-finance-professionals", title: "AI Writing for Finance Professionals: Reports, Analysis, and Client Updates", date: "2026-05-25" },
  { slug: "ai-writing-for-hr-teams", title: "AI Writing for HR Teams: Job Descriptions, Policies, and Internal Updates", date: "2026-05-25" },
  { slug: "ai-writing-for-saas-landing-pages", title: "How to Use AI to Write SaaS Landing Pages That Convert", date: "2026-05-25" },
  { slug: "ai-writing-for-cold-emails", title: "AI Writing for Cold Emails: Templates That Actually Get Replies", date: "2026-05-25" },
  { slug: "ai-writing-for-press-releases", title: "How to Write Press Releases with AI: Format, Tone, and Distribution", date: "2026-05-25" },
  { slug: "ai-writing-for-case-studies", title: "AI Writing for Case Studies: Structure, Storytelling, and Results", date: "2026-05-25" },
  { slug: "ai-writing-for-white-papers", title: "How to Use AI to Draft White Papers: Research, Structure, and Authority", date: "2026-05-25" },
  { slug: "ai-writing-tools-for-students", title: "Best AI Writing Tools for Students: Essays, Research, and More (2026)", date: "2026-05-25" },
  { slug: "ai-writing-vs-human-editors", title: "AI Writing vs Human Editors: When to Use Which for Best Results", date: "2026-05-25" },
  { slug: "how-to-fine-tune-ai-writing-output", title: "How to Fine-Tune AI Writing Output: Prompts, Feedback, and Iteration", date: "2026-05-25" },
  { slug: "ai-writing-for-news-articles", title: "AI Writing for News Articles: Speed, Accuracy, and Ethics", date: "2026-05-25" },
  { slug: "ai-writing-for-grant-proposals", title: "AI Writing for Grant Proposals: How to Make Your Case Compelling", date: "2026-05-25" },
  { slug: "ai-writing-for-resumes-cover-letters", title: "AI Writing for Resumes and Cover Letters: Stand Out in 2026", date: "2026-05-25" },
  { slug: "ai-writing-for-product-reviews", title: "How to Use AI to Write Honest, Engaging Product Reviews", date: "2026-05-25" },
  { slug: "ai-writing-for-event-descriptions", title: "AI Writing for Event Descriptions: Sell More Tickets with Better Copy", date: "2026-05-25" },
  { slug: "ai-writing-for-sales-scripts", title: "AI Writing for Sales Scripts: Cold Calls, Demos, and Follow-Ups", date: "2026-05-25" },
  { slug: "ai-writing-for-onboarding-emails", title: "AI Writing for Onboarding Emails: Welcome Sequences That Retain Users", date: "2026-05-25" },
  { slug: "ai-writing-for-crisis-communications", title: "AI Writing for Crisis Communications: Tone, Timing, and Transparency", date: "2026-05-25" },
  { slug: "ai-writing-tools-for-enterprise-2026", title: "Enterprise AI Writing Tools in 2026: Security, Compliance, and Scale", date: "2026-05-25" },
  { slug: "ai-writing-beginner-guide-2026", title: "AI Writing for Absolute Beginners: Everything You Need to Know (2026)", date: "2026-05-25" },
  { slug: "ai-writing-for-restaurant-menus", title: "AI Writing for Restaurant Menus: Descriptions That Make Mouths Water", date: "2026-05-25" },
  { slug: "ai-writing-for-travel-blogs", title: "AI Writing for Travel Blogs: Capturing Experiences with Authentic Voice", date: "2026-05-25" },
  { slug: "ai-writing-for-fashion-descriptions", title: "AI Writing for Fashion: Product Descriptions That Sell Style", date: "2026-05-25" },
  { slug: "ai-writing-for-sports-commentary", title: "AI Writing for Sports: Commentary, Recaps, and Analysis", date: "2026-05-25" },
  { slug: "ai-writing-for-gaming-content", title: "AI Writing for Gaming: Reviews, Guides, and Community Posts", date: "2026-05-25" },
  { slug: "ai-writing-for-music-reviews", title: "AI Writing for Music Reviews: Describing Sound with Words", date: "2026-05-25" },
  { slug: "ai-writing-for-art-descriptions", title: "AI Writing for Art: Gallery Notes, Artist Statements, and Critiques", date: "2026-05-25" },
  { slug: "ai-writing-for-photography-blogs", title: "AI Writing for Photographers: Captions, Stories, and Portfolio Descriptions", date: "2026-05-25" },
  { slug: "ai-writing-for-cooking-recipes", title: "AI Writing for Food Bloggers: Recipes, Stories, and SEO Tips", date: "2026-05-25" },
  { slug: "ai-writing-for-pet-blogs", title: "AI Writing for Pet Bloggers: Care Guides, Reviews, and Personal Stories", date: "2026-05-25" },
  { slug: "ai-writing-for-diy-tutorials", title: "AI Writing for DIY Tutorials: Step-by-Step Instructions That Anyone Can Follow", date: "2026-05-25" },
  { slug: "ai-writing-for-gardening-blogs", title: "AI Writing for Gardening: Seasonal Guides, Plant Care, and Design Tips", date: "2026-05-25" },
  { slug: "ai-writing-for-fitness-coaches", title: "AI Writing for Fitness Coaches: Workout Plans, Nutrition Tips, and Motivation", date: "2026-05-25" },
  { slug: "ai-writing-for-beauty-bloggers", title: "AI Writing for Beauty Bloggers: Reviews, Tutorials, and Trends", date: "2026-05-25" },
  { slug: "ai-writing-for-parenting-blogs", title: "AI Writing for Parenting Blogs: Sharing Stories That Resonate", date: "2026-05-25" },
  { slug: "ai-writing-for-mental-health", title: "AI Writing for Mental Health: Sensitive, Accurate, and Compassionate Content", date: "2026-05-25" },
  { slug: "ai-writing-for-environmental-topics", title: "AI Writing for Environmental Topics: Communicating Climate Science Effectively", date: "2026-05-25" },
  { slug: "ai-writing-for-local-businesses", title: "AI Writing for Local Businesses: SEO, Community, and Customer Stories", date: "2026-05-25" },
  { slug: "ai-writing-for-personal-branding", title: "AI Writing for Personal Branding: LinkedIn, Twitter, and Beyond", date: "2026-05-25" },
  { slug: "ai-writing-tools-complete-guide-2026", title: "The Complete Guide to AI Writing Tools in 2026: Everything You Need to Know", date: "2026-05-25" },
  { slug: "ai-writing-tools-for-small-teams-2026", title: "Best AI Writing Tools for Small Teams in 2026", date: "2026-05-26" },
  { slug: "ai-writing-for-indie-hackers", title: "AI Writing for Indie Hackers: Build Your Audience Fast", date: "2026-05-26" },
  { slug: "ai-writing-for-solopreneurs", title: "How Solopreneurs Can 10x Content Output with AI Writing", date: "2026-05-26" },
  { slug: "ai-writing-for-creative-agencies", title: "AI Writing for Creative Agencies: Pitch Decks and Proposals", date: "2026-05-26" },
  { slug: "ai-writing-for-non-technical-founders", title: "AI Writing for Non-Technical Founders: From Idea to Content", date: "2026-05-26" },
  { slug: "ai-writing-vs-traditional-copywriting", title: "AI Writing vs Traditional Copywriting: A Balanced Comparison", date: "2026-05-26" },
  { slug: "ai-writing-roi-calculation", title: "How to Calculate the ROI of AI Writing Tools", date: "2026-05-26" },
  { slug: "ai-writing-for-ux-copy", title: "AI Writing for UX Copy: Microcopy That Guides Users", date: "2026-05-26" },
  { slug: "ai-writing-for-chatbots", title: "AI Writing for Chatbot Scripts: Conversational UX", date: "2026-05-26" },
  { slug: "ai-writing-for-push-notifications", title: "Writing Push Notifications That Users Actually Tap", date: "2026-05-26" },
  { slug: "ai-writing-for-sms-marketing", title: "AI Writing for SMS Marketing: 160 Characters to Convert", date: "2026-05-26" },
  { slug: "ai-writing-for-billboards", title: "Can AI Write Billboards? Exploring Creative Limits", date: "2026-05-26" },
  { slug: "ai-writing-for-video-scripts", title: "AI Writing for Video Scripts: From YouTube to TikTok", date: "2026-05-26" },
  { slug: "ai-writing-for-webinars", title: "AI Writing for Webinar Scripts: Engage and Convert", date: "2026-05-26" },
  { slug: "ai-writing-for-online-courses", title: "Creating Online Course Content with AI Writing Tools", date: "2026-05-26" },
  { slug: "ai-writing-for-ebooks", title: "How to Write an eBook with AI: From Outline to Publication", date: "2026-05-26" },
  { slug: "ai-writing-for-whitepapers", title: "AI Writing for Whitepapers: Research-Backed Authority Content", date: "2026-05-26" },
  { slug: "ai-writing-for-annual-reports", title: "Streamlining Annual Reports with AI Writing", date: "2026-05-26" },
  { slug: "ai-writing-localization", title: "AI Writing for Localization: Adapting Content Across Cultures", date: "2026-05-26" },
  { slug: "ai-writing-tools-roadmap-2027", title: "AI Writing Tools in 2027: A Look Ahead", date: "2026-05-26" },
  { slug: "ai-writing-amazon-bullet-points-tutorial", title: "How to Write Amazon Bullet Points That Convert: AI-Powered Tutorial (2026)", date: "2026-05-27" },
  { slug: "ai-writing-shopify-product-descriptions", title: "Shopify Product Descriptions with AI: A Step-by-Step Optimization Guide", date: "2026-05-27" },
  { slug: "ai-writing-etsy-seo-tutorial", title: "Etsy SEO Writing with AI: Tags, Titles, and Descriptions That Rank", date: "2026-05-27" },
  { slug: "ai-writing-google-ads-headlines-tutorial", title: "Writing Google Ads Headlines with AI: A/B Testing Results Inside", date: "2026-05-27" },
  { slug: "ai-writing-blog-outline-tutorial", title: "How to Create Perfect Blog Outlines with AI: From Keyword to Structure", date: "2026-05-27" },
  { slug: "ai-writing-email-sequences-tutorial", title: "AI-Powered Email Sequences: Welcome, Nurture, Convert — Full Tutorial", date: "2026-05-27" },
  { slug: "ai-writing-social-media-calendar", title: "Build a Month of Social Media Content with AI: Complete Calendar Guide", date: "2026-05-27" },
  { slug: "ai-writing-press-release-tutorial", title: "How to Write a Press Release with AI: Format, Quotes, and Distribution", date: "2026-05-27" },
  { slug: "ai-writing-product-review-tutorial", title: "Writing Trustworthy Product Reviews with AI: Ethical Guidelines and Templates", date: "2026-05-27" },
  { slug: "ai-writing-local-seo-tutorial", title: "Local SEO Writing with AI: Google Business Profile Posts and Local Pages", date: "2026-05-27" },
];

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = 'https://tryaiwriter.com';
  const now = new Date();
  
  return [
    {
      url: baseUrl,
      lastModified: now,
      changeFrequency: 'daily' as const,
      priority: 1,
    },
    {
      url: `${baseUrl}/pricing`,
      lastModified: now,
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/blog`,
      lastModified: now,
      changeFrequency: 'daily' as const,
      priority: 0.7,
    },
    ...blogPosts.map((post) => ({
      url: `${baseUrl}/blog/${post.slug}`,
      lastModified: new Date(post.date),
      changeFrequency: 'monthly' as const,
      priority: 0.6,
    })),
  ];
}